### ISSUE TITLE
ImportError: cannot import name 'Builder'

### ISSUE THREAD

**Issue by ldong87** [aws-samples/amazon-sagemaker-bert-classify-pytorch#1]
Builder class is absent in your current branch thus producing the following error:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from builder import Builder
ImportError: cannot import name 'Builder'

**Comment by elangovana** [comment]
Hi Thanks for raising the issue. Apologies for the delay in getting back to you. The problem you are facing is related to how Python searches for modules...  

```bash
# This will make sure that all module in ./src are visible 
export PYTHONPATH=./src
```

Alternatively, you could also do this in within python


```python
import sys
sys.path.append('src')
```

**Comment by ldong87** [comment]
Thanks for the reply.
But I think the problem is you change the class name from Builder to Train in one of your commit: https://github.com/aws-samples/amazon-sagemaker-bert-classify-pytorch/commit/a29479b20726751e9872671f1ef7230a1c7aa7dd#diff-d5ab0c58b897da1e9dd07b2925168310L33

**Comment by snowolf** [comment]
As you have changed Builder to Train, however, the main.py don't modify, still use:

b = Builder(train_data=train_data_file, val_data=val_data_file, labels_file=classes_file,
                checkpoint_dir=args.checkpointdir, epochs=args.epochs,
                early_stopping_patience=args.earlystoppingpatience, batch_size=args.batch, max_seq_len=args.maxseqlen,
                learning_rate=args.lr, fine_tune=args.finetune, model_dir=args.modeldir)

As the parameters are different between Builder and Train, I think you should modify this part code too.

**Comment by elangovana** [comment]
OOPS!!! That was a mistake Thanks for pointing it out. Fixed up..
