### ISSUE TITLE
UnexpectedStatusException: Error for Training job pytorch-training-2020-10-26-17-35-06-746: Failed. Reason: AlgorithmError: ExecuteUserScriptError: Command "/opt/conda/bin/python train_deploy.py --backend gloo --epochs 1 --num_labels 2"

### ISSUE THREAD

**Issue by aarsanjani** [aws-samples/amazon-sagemaker-bert-classify-pytorch#2]
UnexpectedStatusException: Error for Training job pytorch-training-2020-10-26-17-35-06-746: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/opt/conda/bin/python train_deploy.py --backend gloo --epochs 1 --num_labels 2"

when running training

**Comment by elangovana** [comment]
Hi Ali,  Looks like this error is related to a different sample https://github.com/aws-samples/amazon-sagemaker-bert-pytorch, so you might want to log the issue in that repo . But you are more than welcome to use this sample too :-)
